### ISSUE TITLE
Not working in Colab

### ISSUE THREAD

**Issue by Zongqian167** [cytronicoder/biorsp#1]
Hi there, I was trying to use biorsp module in Colab environment, but couldn't get it installed.

![image](https://github.com/cytronicoder/biorsp/assets/72328229/c82efb81-c457-43c8-b586-b09a89394b44)

**Comment by cytronicoder** [comment]
Should be patched in https://github.com/cytronicoder/biorsp/commit/a25a6dfdf5ba3c351fdb1e0c4bb1737ae548e642!
